/**
* PROBLEM #2
*
*    Each new term in the Fibonacci sequence is generated by adding the
*    previous two terms. By starting with 1 and 2, the first 10 terms will be:
*                      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
*    By considering the terms in the Fibonacci sequence whose values do not
*    exceed four million, find the sum of the even-valued terms.
*
*/

module.exports = function(max) {
    var sum = 0, num = 0, f = fib(num);
    while (f < max) {
        if (f % 2 === 0) sum += f;
        f = fib(++num);
    }
    return sum;
}

// Returns the nth Fibonacci number, starting from 1 and 2
var fibNums = [ 1, 2 ];
function fib(n) {
    if (fibNums[n])
        return fibNums[n];
    else {
        fibNums[n] = fib(n-1) + fib(n-2);
        return fibNums[n];
    }
}
